### ISSUE TITLE
Include Default Values for Config

### ISSUE THREAD

**Issue by jojonas** [pfirsich/Frontdown#5]
The current version (importing a module) does not allow for default values. Using eval() and a globals dict, this would be possible. There are probably more options though...

**Comment by pfirsich** [comment]
Also I would really like if it was not possible to get or set invalid configuration values. Initially I decided against JSON, because I thought of comments as a mandatory feature for the config (and still do), but I didn't want to fight with stipping comments properly and thought this might be the easier option. But it starts becoming increasingly complicated. So I will implement .json-configurations with comments.

EDIT: I found [JSON.minify](https://github.com/getify/JSON.minify/tree/python), which will make this a lot easier.

**Comment by pfirsich** [comment]
I'm done now and waiting for Jonas to approve the changes and handle the pull request. (#11)
